=== ddacmx/constructor-event-prediction/configs/schemas/split-manifest.v1.schema.json
{"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"split-manifest.v1","type":"object","additionalProperties":false,"required":["schema_version","seed","train_ids","validation_ids","test_ids"],"properties":{"schema_version":{"const":"split-manifest.v1"},"seed":{"type":"integer"},"train_ids":{"type":"array","minItems":1,"uniqueItems":true,"items":{"type":"string","pattern":"^seq-[0-9]{6}$"}},"validation_ids":{"type":"array","minItems":1,"uniqueItems":true,"items":{"type":"string","pattern":"^seq-[0-9]{6}$"}},"test_ids":{"type":"array","minItems":1,"uniqueItems":true,"items":{"type":"string","pattern":"^seq-[0-9]{6}$"}}}}

=== ddacmx/constructor-event-prediction/artifacts/final/runs/7b9514e839241507f358/split-seed-20261021.json
{"schema_version":"split-manifest.v1","seed":20271021,"test_ids":["seq-003379","seq-000854","seq-007736","seq-004877","seq-003218","seq-009337","seq-007570","seq-005963","seq-009704","seq-008271","seq-008771","seq-004356","seq-004960","seq-006035","seq-003408","seq-004106","seq-007370","seq-001896","seq-008338","seq-002258","seq-001381","seq-007649","seq-008935","seq-008631","seq-002318","seq-007675","seq-003731","seq-000660","seq-003141","seq-001400","seq-000833","seq-004584","seq-009840","seq-001614","seq-000141","seq-008911","seq-008157","seq-005730","seq-004999","seq-004468","seq-001615","seq-004245","seq-008110","seq-006739","seq-001890","seq-009633","seq-005847","seq-008371","seq-005456","seq-001402","seq-006842","seq-005150","seq-001028","seq-003185","seq-004679","seq-001262","seq-002276","seq-008645","seq-002879","seq-001305","seq-006274","seq-003748","seq-001089","seq-008544","seq-003745","seq-006692","seq-001601","seq-002902","seq-006254","seq-003945","seq-002710","seq-000553","seq-004727","seq-005133","seq-006330","seq-005524","seq-004672","seq-004586","seq-005399","seq-001073","seq-007733","seq-006745","seq-000625","seq-004893","seq-002355","seq-007387","seq-009194","seq-003183","seq-009577","seq-003809","seq-005591","seq-004058","seq-003590","seq-008541","seq-002291","seq-008590","seq-006004","seq-006817","seq-004794","seq-003244","seq-005241","seq-009122","seq-003693","seq-007869","seq-005588","seq-005600","seq-008942","seq-003199","seq-006670","seq-004896","seq-008936","seq-008601","seq-002254","seq-003387","seq-005142","seq-000899","seq-006158","seq-007314","seq-005884","seq-001925","seq-003290","seq-008424","seq-000516","seq-000440","seq-005746","seq-002852","seq-006144","seq-007434","seq-004574","seq-002062","seq-005212","seq-004542","seq-004418","seq-003251","seq-003223","seq-000787","seq-009271","seq-002255","seq-006493","seq-005586","seq-005304","seq-008606","seq-006257","seq-007469","seq-006209","seq-004514","seq-008285","seq-003662","seq-007957","seq-006807","seq-007536","seq-008678","seq-002821","seq-005417","seq-008523","seq-007902","seq-000565","seq-005659","seq-003359","seq-000538","seq-003454","seq-008441","seq-003222","seq-006394","seq-009393","seq-009609","seq-007889","seq-006460","seq-000414","seq-000011","seq-000646","seq-004475","seq-006227","seq-006496","seq-004487","seq-003230","seq-008401","seq-004140","seq-003132","seq-001772","seq-001271","seq-008402","seq-002754","seq-003020","seq-007809","seq-004467","seq-005750","seq-006939","seq-003931","seq-006165","seq-003614","seq-001244","seq-009950","seq-001664","seq-005778","seq-008510","seq-005714","seq-000977","seq-007741","seq-005792","seq-001062","seq-002586","seq-006116","seq-005087","seq-005258","seq-006749","seq-002818","seq-001446","seq-004179","seq-008609","seq-002888","seq-003711","seq-009846","seq-008239","seq-005127","seq-001275","seq-004518","seq-003124","seq-001540","seq-001548","seq-009127","seq-002046","seq-003225","seq-002542","seq-008229","seq-002688","seq-000502","seq-007204","seq-009438","seq-006667","seq-002367","seq-003260","seq-000972","seq-005093","seq-000590","seq-002882","seq-009382","seq-006050","seq-005045","seq-001828","seq-003422","seq-009686","seq-001694","seq-002552","seq-008925","seq-009768","seq-003370","seq-008011","seq-002052","seq-002536","seq-007216","seq-008339","seq-008217","seq-002122","seq-002985","seq-003761","seq-007290","seq-005507","seq-008482","seq-004582","seq-008136","seq-001784","seq-006073","seq-006259","seq-000426","seq-001718","seq-007894","seq-006709","seq-003307","seq-001490","seq-007228","seq-004610","seq-000736","seq-001403","seq-007409","seq-000215","seq-005310","seq-003403","seq-008574","seq-000005","seq-003288","seq-005667","seq-008917","seq-001836","seq-004432","seq-004277","seq-006888","seq-006402","seq-004528","seq-006090","seq-006651","seq-004080","seq-007321","seq-006971","seq-002185","seq-000829","seq-001176","seq-001188","seq-009724","seq-000057","seq-006077","seq-001848","seq-004283","seq-006801","seq-006664","seq-003113","seq-008301","seq-001965","seq-009096","seq-007843","seq-000461","seq-004110","seq-004717","seq-008854","seq-007151","seq-006492","seq-001020","seq-008259","seq-009667","seq-002832","seq-002533","seq-004286","seq-004450","seq-002954","seq-009502","seq-007685","seq-000848","seq-009447","seq-009068","seq-005641","seq-005805","seq-005757","seq-006882","seq-007430","seq-004033","seq-007690","seq-004769","seq-005715","seq-003402","seq-005601","seq-008187","seq-001038","seq-002780","seq-007951","seq-002581","seq-007873","seq-000714","seq-009987","seq-009214","seq-000045","seq-007787","seq-004163","seq-004043","seq-001371","seq-009810","seq-004194","seq-008584","seq-000315","seq-007867","seq-009624","seq-001054","seq-000747","seq-007507","seq-000794","seq-002719","seq-009285","seq-003115","seq-002543","seq-003212","seq-007983","seq-002307","seq-002994","seq-004353","seq-008359","seq-000522","seq-005656","seq-009478","seq-003059","seq-004764","seq-001950","seq-002975","seq-007961","seq-000217","seq-005744","seq-002792","seq-002134","seq-006501","seq-000416","seq-003735","seq-008555","seq-000441","seq-005628","seq-008858","seq-009101","seq-003302","seq-005467","seq-006323","seq-005225","seq-005595","seq-002992","seq-004818","seq-000418","seq-008921","seq-001421","seq-008064","seq-001964","seq-006123","seq-000579","seq-008459","seq-007201","seq-006321","seq-006235","seq-002772","seq-004228","seq-007882","seq-008531","seq-001936","seq-003120","seq-006712","seq-002162","seq-007338","seq-005974","seq-005145","seq-003688","seq-001205","seq-000544","seq-001656","seq-002849","seq-004200","seq-001238","seq-005390","seq-004867","seq-003410","seq-006821","seq-001031","seq-002268","seq-004038","seq-005558","seq-005246","seq-000782","seq-008681","seq-003400","seq-003603","seq-003878","seq-002450","seq-007101","seq-000521","seq-009124","seq-002966","seq-008629","seq-002972","seq-009137","seq-005362","seq-005139","seq-006752","seq-003919","seq-000401","seq-002021","seq-004650","seq-001712","seq-006484","seq-000891","seq-001070","seq-005816","seq-008550","seq-009948","seq-005727","seq-000229","seq-006764","seq-009864","seq-003332","seq-003398","seq-003600","seq-001792","seq-002908","seq-004334","seq-000688","seq-007711","seq-003690","seq-004883","seq-002271","seq-003894","seq-003490","seq-006192","seq-000618","seq-009611","seq-001196","seq-003967","seq-001891","seq-004918","seq-002076","seq-006808","seq-000313","seq-005818","seq-003173","seq-002275","seq-003350","seq-009669","seq-004235","seq-004462","seq-002415","seq-008955","seq-001222","seq-005569","seq-006784","seq-004331","seq-006251","seq-003063","seq-007851","seq-002464","seq-008461","seq-003960","seq-003608","seq-009341","seq-009011","seq-004616","seq-006741","seq-001725","seq-008827","seq-000505","seq-004360","seq-005571","seq-004588","seq-006391","seq-007512","seq-003532","seq-001453","seq-007641","seq-007366","seq-008085","seq-003993","seq-004169","seq-004278","seq-005054","seq-007621","seq-009480","seq-008520","seq-002186","seq-005090","seq-004303","seq-001561","seq-004943","seq-002395","seq-008447","seq-005581","seq-009377","seq-001344","seq-009136","seq-008519","seq-001812","seq-009976","seq-004394","seq-003517","seq-006108","seq-001741","seq-001277","seq-000466","seq-008517","seq-004965","seq-007194","seq-008780","seq-006020","seq-007598","seq-009055","seq-009269","seq-002626","seq-006220","seq-006908","seq-004439","seq-000968","seq-002234","seq-003850","seq-006727","seq-008021","seq-000786","seq-000174","seq-006120","seq-002333","seq-007407","seq-001264","seq-004954","seq-008516","seq-003956","seq-005542","seq-003367","seq-000294","seq-003860","seq-005041","seq-000058","seq-008621","seq-003420","seq-008260","seq-005828","seq-008358","seq-005951","seq-004762","seq-003978","seq-005933","seq-006103","seq-002712","seq-006877","seq-003348","seq-003545","seq-009504","seq-003940","seq-006331","seq-004152","seq-008915","seq-003952","seq-006160","seq-003325","seq-007028","seq-009052","seq-003366","seq-004341","seq-007667","seq-004573","seq-001985","seq-000195","seq-000143","seq-009693","seq-004074","seq-009446","seq-008710","seq-000954","seq-009281","seq-005900","seq-004691","seq-008580","seq-009814","seq-001417","seq-006523","seq-004864","seq-007997","seq-008400","seq-009785","seq-004664","seq-001485","seq-002337","seq-001771","seq-008364","seq-008224","seq-003672","seq-005686","seq-006570","seq-000731","seq-003508","seq-001530","seq-007373","seq-003423","seq-008862","seq-006834","seq-007084","seq-008966","seq-009809","seq-008929","seq-008960","seq-006833","seq-006613","seq-009893","seq-007239","seq-003887","seq-002087","seq-003544","seq-002244","seq-001202","seq-002168","seq-001407","seq-004054","seq-006581","seq-000846","seq-008823","seq-001263","seq-007108","seq-008027","seq-004259","seq-006550","seq-002351","seq-006473","seq-008040","seq-003880","seq-005602","seq-006051","seq-000261","seq-003130","seq-001208","seq-001198","seq-003301","seq-008084","seq-008395","seq-002018","seq-006590","seq-003658","seq-008660","seq-009745","seq-001276","seq-002724","seq-008512","seq-002398","seq-002687","seq-001525","seq-005823","seq-002717","seq-004629","seq-001578","seq-008779","seq-005345","seq-008907","seq-000024","seq-000976","seq-001660","seq-006091","seq-005555","seq-002598","seq-009131","seq-003684","seq-001702","seq-007267","seq-009917","seq-007493","seq-002487","seq-004859","seq-007000","seq-001579","seq-004321","seq-005522","seq-002281","seq-007865","seq-005271","seq-007977","seq-001971","seq-006792","seq-000952","seq-007015","seq-008150","seq-001698","seq-009369","seq-003768","seq-005153","seq-003003","seq-008062","seq-005329","seq-005077","seq-006353","seq-002466","seq-006207","seq-001841","seq-003245","seq-004874","seq-005952","seq-001912","seq-000791","seq-006787","seq-002529","seq-001324","seq-007093","seq-002055","seq-001980","seq-000298","seq-007248","seq-000955","seq-009218","seq-006436","seq-002514","s
